security:
  oauth2:
    client:
      clientId: account-service
#      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      clientSecret: user
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
#      host: account-mongodb
      host: localhost
      username: user
#      password: ${MONGODB_PASSWORD}
      password: user
      database: piggymetrics
      port: 27017

server:
  context-path: /accounts
  port: 6000
