spring:
  data:
    mongodb:
#      host: auth-mongodb
      host: localhost
      username: user
#      password: ${MONGODB_PASSWORD}
      password: user
      database: piggymetrics
      port: 27017

server:
  context-path: /uaa
  port: 5000
